# Generated by Django 4.2.3 on 2023-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_school_year_remove_account_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
