# Generated by Django 4.2.3 on 2023-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(blank=True, choices=[('AGE', 'Agricultural Engineerimg'), ('CSC', 'Computer Science and Engineerimg'), ('CVE', 'Civil Engineerimg'), ('CHE', 'Chemical Engineerimg'), ('FST', 'Food Science and Engineerimg'), ('MSE', 'Material Science and Engineerimg'), ('EEE', 'Electronic and Electrical Engineerimg'), ('MEE', 'Mechanical Engineering')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='school_year',
            field=models.CharField(blank=True, choices=[('first', '100 Level'), ('second', '200 Level'), ('third', '300 Level'), ('fourth', '400 Level'), ('fifth', '500 Level')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='School_year',
        ),
    ]
