# Generated by Django 4.2.3 on 2023-08-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypals', '0003_bottext_chatbox_usertext_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserText',
            new_name='Text',
        ),
    ]
