# Generated by Django 4.2.3 on 2023-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypals', '0005_coursecode_courseoutline_courseunit_delete_bottext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('outline', models.TextField()),
                ('unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CourseCode',
        ),
        migrations.DeleteModel(
            name='CourseOutline',
        ),
        migrations.DeleteModel(
            name='CourseUnit',
        ),
    ]
