# Generated by Django 4.2.3 on 2023-08-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studypals', '0007_alter_course_code_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEE',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='CHE',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='CSC',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='FST',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='MEE',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='MSC',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studypals.course')),
            ],
            bases=('studypals.course',),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.TextField()),
                ('tue', models.TextField()),
                ('wed', models.TextField()),
                ('thu', models.TextField()),
                ('fri', models.TextField()),
            ],
        ),
    ]
