# Generated by Django 4.2.3 on 2023-08-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypals', '0009_remove_che_course_ptr_remove_csc_course_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aeeCourse',
        ),
        migrations.DeleteModel(
            name='cheCourse',
        ),
        migrations.DeleteModel(
            name='cscCourse',
        ),
        migrations.DeleteModel(
            name='cveCourse',
        ),
        migrations.DeleteModel(
            name='eeeCourse',
        ),
        migrations.DeleteModel(
            name='fstCourse',
        ),
        migrations.DeleteModel(
            name='meeCourse',
        ),
        migrations.DeleteModel(
            name='mscCourse',
        ),
    ]
